// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: exporter/exporterhelper/internal/cache/meta.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sizer type configuration
type SizerType int32

const (
	SizerType_REQUESTS SizerType = 0
	SizerType_ITEMS    SizerType = 1
	SizerType_BYTES    SizerType = 2
)

// Enum value maps for SizerType.
var (
	SizerType_name = map[int32]string{
		0: "REQUESTS",
		1: "ITEMS",
		2: "BYTES",
	}
	SizerType_value = map[string]int32{
		"REQUESTS": 0,
		"ITEMS":    1,
		"BYTES":    2,
	}
)

func (x SizerType) Enum() *SizerType {
	p := new(SizerType)
	*p = x
	return p
}

func (x SizerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SizerType) Descriptor() protoreflect.EnumDescriptor {
	return file_exporter_exporterhelper_internal_cache_meta_proto_enumTypes[0].Descriptor()
}

func (SizerType) Type() protoreflect.EnumType {
	return &file_exporter_exporterhelper_internal_cache_meta_proto_enumTypes[0]
}

func (x SizerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SizerType.Descriptor instead.
func (SizerType) EnumDescriptor() ([]byte, []int) {
	return file_exporter_exporterhelper_internal_cache_meta_proto_rawDescGZIP(), []int{0}
}

// CacheMetadata holds all persistent metadata for the cache.
type CacheMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sizer type configuration.
	SizerType SizerType `protobuf:"varint,1,opt,name=sizer_type,json=sizerType,proto3,enum=opentelemetry.collector.exporter.exporterhelper.internal.cache.SizerType" json:"sizer_type,omitempty"`
	// Current total size of the cache (in bytes, items, or requests).
	CacheSize int64 `protobuf:"fixed64,2,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	// Index where the next item will be written to the cache.
	WriteIndex uint64 `protobuf:"fixed64,3,opt,name=write_index,json=writeIndex,proto3" json:"write_index,omitempty"`
	// List of item indices currently being processed by consumers.
	CurrentlyDispatchedItems []uint64 `protobuf:"fixed64,4,rep,packed,name=currently_dispatched_items,json=currentlyDispatchedItems,proto3" json:"currently_dispatched_items,omitempty"`
	// List of item indices to be dispatched to consumers.
	ItemsToDispatch []uint64 `protobuf:"fixed64,5,rep,packed,name=items_to_dispatch,json=itemsToDispatch,proto3" json:"items_to_dispatch,omitempty"`
}

func (x *CacheMetadata) Reset() {
	*x = CacheMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exporter_exporterhelper_internal_cache_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMetadata) ProtoMessage() {}

func (x *CacheMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_exporterhelper_internal_cache_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMetadata.ProtoReflect.Descriptor instead.
func (*CacheMetadata) Descriptor() ([]byte, []int) {
	return file_exporter_exporterhelper_internal_cache_meta_proto_rawDescGZIP(), []int{0}
}

func (x *CacheMetadata) GetSizerType() SizerType {
	if x != nil {
		return x.SizerType
	}
	return SizerType_REQUESTS
}

func (x *CacheMetadata) GetCacheSize() int64 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *CacheMetadata) GetWriteIndex() uint64 {
	if x != nil {
		return x.WriteIndex
	}
	return 0
}

func (x *CacheMetadata) GetCurrentlyDispatchedItems() []uint64 {
	if x != nil {
		return x.CurrentlyDispatchedItems
	}
	return nil
}

func (x *CacheMetadata) GetItemsToDispatch() []uint64 {
	if x != nil {
		return x.ItemsToDispatch
	}
	return nil
}

var File_exporter_exporterhelper_internal_cache_meta_proto protoreflect.FileDescriptor

var file_exporter_exporterhelper_internal_cache_meta_proto_rawDesc = []byte{
	0x0a, 0x31, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x3e, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x68, 0x65,
	0x6c, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x22, 0xa3, 0x02, 0x0a, 0x0d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x68, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x49, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x65, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x10, 0x52, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x3c, 0x0a, 0x1a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x79, 0x5f, 0x64, 0x69, 0x73,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x06, 0x52, 0x18, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x79, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2a, 0x0a,
	0x11, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x54,
	0x6f, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2a, 0x2f, 0x0a, 0x09, 0x53, 0x69, 0x7a,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x54, 0x45, 0x4d, 0x53, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x02, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x6f,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x69,
	0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x68, 0x65, 0x6c,
	0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exporter_exporterhelper_internal_cache_meta_proto_rawDescOnce sync.Once
	file_exporter_exporterhelper_internal_cache_meta_proto_rawDescData = file_exporter_exporterhelper_internal_cache_meta_proto_rawDesc
)

func file_exporter_exporterhelper_internal_cache_meta_proto_rawDescGZIP() []byte {
	file_exporter_exporterhelper_internal_cache_meta_proto_rawDescOnce.Do(func() {
		file_exporter_exporterhelper_internal_cache_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_exporter_exporterhelper_internal_cache_meta_proto_rawDescData)
	})
	return file_exporter_exporterhelper_internal_cache_meta_proto_rawDescData
}

var file_exporter_exporterhelper_internal_cache_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exporter_exporterhelper_internal_cache_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exporter_exporterhelper_internal_cache_meta_proto_goTypes = []interface{}{
	(SizerType)(0),        // 0: opentelemetry.collector.exporter.exporterhelper.internal.cache.SizerType
	(*CacheMetadata)(nil), // 1: opentelemetry.collector.exporter.exporterhelper.internal.cache.CacheMetadata
}
var file_exporter_exporterhelper_internal_cache_meta_proto_depIdxs = []int32{
	0, // 0: opentelemetry.collector.exporter.exporterhelper.internal.cache.CacheMetadata.sizer_type:type_name -> opentelemetry.collector.exporter.exporterhelper.internal.cache.SizerType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exporter_exporterhelper_internal_cache_meta_proto_init() }
func file_exporter_exporterhelper_internal_cache_meta_proto_init() {
	if File_exporter_exporterhelper_internal_cache_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exporter_exporterhelper_internal_cache_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exporter_exporterhelper_internal_cache_meta_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exporter_exporterhelper_internal_cache_meta_proto_goTypes,
		DependencyIndexes: file_exporter_exporterhelper_internal_cache_meta_proto_depIdxs,
		EnumInfos:         file_exporter_exporterhelper_internal_cache_meta_proto_enumTypes,
		MessageInfos:      file_exporter_exporterhelper_internal_cache_meta_proto_msgTypes,
	}.Build()
	File_exporter_exporterhelper_internal_cache_meta_proto = out.File
	file_exporter_exporterhelper_internal_cache_meta_proto_rawDesc = nil
	file_exporter_exporterhelper_internal_cache_meta_proto_goTypes = nil
	file_exporter_exporterhelper_internal_cache_meta_proto_depIdxs = nil
}
